# Generated by Django 3.0.8 on 2020-09-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200902_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followers',
            new_name='following',
        ),
    ]
